articles/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

app_name="articles"

urlpatterns = [
    path('', views.main_page, name='index'),
    path('<int:id>', views.article_description, name='article'),
    path('add/', views.article_add, name='article_add'),
#    path('<int:id>/comment/', views.CommentListView.get_queryset(), name='comment_list'),
    path('comment/', views.CommentListView.as_view(), name='comment_list'),
    path('comment-one/<int:pk>/', views.CommentDetailView.as_view(), name='comment_one'),
    path('comment-update/<int:pk>/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comment-delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment_delete'),
    path('comment-create/', views.CommentCreateView.as_view(), name='comment_create'),
]

djangoblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from djangoblog import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls', namespace='articles')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    article_name = models.CharField(max_length = 100)
    article_text = models.TextField(max_length = 10000)
    article_date = models.DateTimeField('date published', null=True)
    article_img = models.ImageField(upload_to='articles', null=True, blank=True)

    def __str__(self):
        return f'{self.article_name}, published: {self.article_date}'

class Comment(models.Model):
    comment_autr = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    comment_autor = models.CharField(max_length = 50, null=True)
    comment_text = models.CharField(max_length = 1000)
    comment_artc = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.comment_autr}-{self.comment_text}'

articles/forms.py
from django import forms
from .models import Article


class CommentForm(forms.Form):
    name = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

class  ArticleForm(forms.ModelForm):
    article_name = forms.CharField(label='Название статьи')
    article_text = forms.CharField(label='Текст статьи')
    class Meta:
        model = Article
        #fields = '__all__'
        fields = ('article_name', 'article_text','article_img')
        #exclude = ('article_date')

articles/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import Article, Comment
from .forms import CommentForm, ArticleForm
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views (представление) here.

def main_page(request):
    art_all = Article.objects.all()
    return render(request, 'articles/category.html', {'articles':art_all})


def article_description(request,id):
    art_one = get_object_or_404(Article, id=id)
    comments = Comment.objects.filter(comment_artc=art_one)
#    comments = Comment.objects.all()
    print(comments)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            message = form.cleaned_data['message']
            print(f'{name}, {message}')
            article_object = Comment(comment_autor=name, comment_text=message, comment_artc=art_one)
            article_object.save()
            return render(request, 'articles/single.html', {'article': art_one, 'comments': comments, 'form': form})
    else:
        form = CommentForm()
        return render(request, 'articles/single.html', {'article': art_one, 'comments': comments, 'form': form})

def article_add(request):
    if request.method == 'GET':
        form = ArticleForm()
        return render(request, 'articles/article_add.html', {'form': form})
    else:
        form = ArticleForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('articles:index'))
        else:
            return render(request, 'articles/article_add.html', {'form': form})

class CommentListView(ListView):
    model = Comment
    template_name = 'articles/comment_list.html'
    context_object_name = 'comments'

    #def get_queryset(self,id):
    # можно наложить условия на объекты
        #return Comment.objects.filter(comment_artc=id)

class CommentDetailView(DetailView):
    model = Comment
    template_name = 'articles/comment_one.html'


class CommentUpdateView(UpdateView):
    template_name = 'articles/comment_update.html'
    model = Comment
    success_url = reverse_lazy('articles:comment_list')

class CommentDeleteView(DeleteView):
    template_name = 'articles/comment_delete.html'
    model = Comment
    success_url = reverse_lazy('articles:comment_list')

class CommentCreateView(CreateView):
    template_name = 'articles/comment_create.html'
    model = Comment
    fields = '__all__'
    success_url = reverse_lazy('articles:comment_list')

djangoblog/views.py
from django.shortcuts import render
from articles.models import Article

def home_page(request):
    art_one = Article.objects.first()
    return render(request,"articles/index.html",{'article':art_one})

articles/templates/articles/article_add.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

          <div class="col-md-4">


        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
            <p>{{field.label_tag}}</p>
                <hr>
                {% for error in field.errors %}
                    {{error}}
                {% endfor %}
            <p>{{field}}</p>
            {% endfor %}

            <button type="submit" >Добавить статью</button>
        </form>

          </div>
        </div>
      </div>
    </div>
{% endblock %}

articles/templates/articles/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Hikers Blog &mdash; Colorlib Website Template</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700|Playfair+Display:400,700,900" rel="stylesheet">

    {% load static %}

    <link rel="stylesheet" href="{% static "articles/fonts/icomoon/style.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/magnific-popup.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/jquery-ui.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/owl.theme.default.min.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/bootstrap-datepicker.css" %}">
    <link rel="stylesheet" href="{% static "articles/fonts/flaticon/font/flaticon.css" %}">
    <link rel="stylesheet" href="{% static "articles/css/aos.css" %}">

    <link rel="stylesheet" href="{% static "articles/css/style.css" %}">
  </head>
  <body>

  <div class="site-wrap">

    <header class="site-navbar pt-3" role="banner">
      <div class="container-fluid">
        <div class="row align-items-center">

          <div class="col-6 col-xl-6 logo">
            <h1 class="mb-0"><a href="index.html" class="text-black h2 mb-0">Hikers</a></h1>
          </div>

           <div class="col-12 d-none d-xl-block border-top">
            <nav class="site-navigation text-center " role="navigation">
              <ul class="site-menu js-clone-nav mx-auto d-none d-lg-block mb-0">
                <li><a href="{% url 'home' %}">Homepage</a></li>
                <li><a href="{% url 'articles:index' %}">All articles</a></li>
                <li><a href="{% url 'articles:article_add' %}">Add article</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </header>
  </div>

   {% block content %} {% endblock %}

      <div class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-12 text-center">
            <p>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy; <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              </p>
          </div>
        </div>
      </div>
    </div>

  </body>
</html>

articles/templates/articles/category.html
{% extends "articles/base.html" %}


{% block content %}
  <div class="site-wrap">

    <div class="site-mobile-menu">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <div class="py-5 bg-light">
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <span>Category</span>
            <h3>All articles</h3>
            <p>The most interesting articles are collected here!</p>
          </div>
        </div>
      </div>
    </div>

    <div class="site-section bg-white">
      <div class="container">
        <div class="row">
          {% for article in articles.all%}
          <div class="col-lg-4 mb-4">
            <div class="entry2">
              <a href="{% url 'articles:article' id=article.id %}"><img src={{article.article_img.url}} alt="Image" class="img-fluid rounded"></a>
              <div class="excerpt">
              <h2><a href="{% url 'articles:article' id=article.id %}">{{article.article_name}}</a></h2>
              <div class="post-meta align-items-center text-left clearfix">

                <span>&nbsp;-&nbsp; {{article.article_date}}</span>
              </div>
              </div>
            </div>
          </div>
        {% endfor %}

        </div>
    </div>
  </div>
    <!-- END main-content -->
{% endblock %}

articles/templates/articles/comment_create.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>

        </div>
      </div>
    </div>
{% endblock %}

articles/templates/articles/comment_delete.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

            <ul>
                <li>{{object.comment_text}}</li>

            <li>Вы уверены?</li>
        <form method="post">
        {% csrf_token %}
            <button type="submit">Да</button>
        </form>
            </ul>

        </div>
      </div>
    </div>
{% endblock %}

articles/templates/articles/comment_list.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">
            <ul>
            {% for comment in comments%}
                <li>
                    <a href = "{%url 'articles:comment_one' pk=comment.pk %}">{{comment.comment_autor}}:{{comment.comment_text}}</a>
                </li>
            {% endfor %}
            </ul>
        </div>
          <a href = "{%url 'articles:comment_create' %}">Создать сомментарий</a>
      </div>
    </div>
{% endblock %}

articles/templates/articles/comment_one.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

            <ul>
                <li>{{comment.comment_autor}}:{{comment.comment_text}}</li>
                <li><a href = "{%url 'articles:comment_update' pk=comment.pk %}">Изменить</a></li>
                <li><a href = "{%url 'articles:comment_delete' pk=comment.pk %}">Удалить</a></li>
            </ul>

        </div>
      </div>
    </div>
{% endblock %}

articles/templates/articles/comment_update.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section bg-light">
      <div class="container">
        <div class="row align-items-stretch retro-layout-2">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>

        </div>
      </div>
    </div>
{% endblock %}

articles/templates/articles/index.html
{% extends "articles/base.html" %}


{% block content %}
    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-12 section-heading"><h2>Popular Posts</h2></div>
            <a href="{% url 'articles:article' id=article.id %}"><img src={{article.article_img.url}} alt="Image" class="img-fluid rounded"></a>
              <div class="text">
                <h2>{{article.article_name}}</h2>
                <span class="date">{{article.article_date}}</span>
              </div>
            </a>
        </div>
      </div>
    </div>

{% endblock %}

articles/templates/articles/single.html
{% extends "articles/base.html" %}


{% block content %}

  <div class="site-wrap">
    <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('images/hero_1.jpg');">
      <div class="container">
        <div class="row same-height justify-content-center">
          <div class="col-md-12 col-lg-10">
            <div class="post-entry text-center">
              <h2>{{article.article_name}}</h2>
              <span class="date">{{article.article_date}}</span>
            </div>
          </div>
        </div>
        <div class="text">{{article.article_text}}</div>
      </div>
    </div>

    <section class="site-section py-lg">
      <div class="container">
        
        <div class="row blog-entries element-animate">

          <div class="col-md-12 col-lg-8 main-content">

            <div class="pt-5">
              <h3 class="mb-5">Comments</h3>
              <ul>
              <!-- <li><a href="{% url 'articles:comment_list'  %}">Comments</a></li> -->

                {% for comment in comments.all%}

                <li>
                  <a href = "{%url 'articles:comment_one' pk=comment.pk %}">
                    {{comment.comment_autor}}:{{comment.comment_text}}
                  </a>
                </li>

                {% endfor %}

                <a href = "{%url 'articles:comment_create' %}">Создать сомментарий</a>


              </ul>
              <!-- END comment-list -->
              
              <div class="comment-form-wrap pt-5">
                <h3 class="mb-5">Leave a comment</h3>
                <form metod="post" enctype="multipart/form-data">
                  {% csrf_token %}

                  {% for field in form %}
                      <p>{{field.label_tag}}</p>
                      <hr>
                        {% for error in field.errors %}
                          {{error}}
                        {% endfor %}
                      <p>{{field}}</p>
                  {% endfor %}

                  <div class="form-group">
                    <input type="submit" value="Post Comment" class="btn btn-primary">
                  </div>

                </form>
              </div>
            </div>

          </div>

          <!-- END main-content -->

 {% endblock %}